server:
  port: 9002


spring:
  application:
    name: feign-consumer # 应用名，可用于替换 RestTemplate 请求的路径名
# Eureka Config
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defualtZone: http://localhost:8761/eureka # Eureka Server URL，根据实际情况编写


ribbon:
  ConnectTimeout: 5000 # 连接超时时间，ms
  ReadTimeout: 5000 # 逻辑超时时间，ms
#feign:
#  client:
#    config:
#      default:
#        ConnectTimeout: 5000 # 连接超时时间，ms
#        ReadTimeout: 5000 # 逻辑超时时间，ms
