server:
  port: 9001

spring:
  cloud:
    stream:
      # 定义绑定器，绑定到哪个消息中间件上
      binders:
        # 自定义的绑定器名称
        my_binder:
          type: rabbit # 绑定器类型
          environment: # 指定mq的环境
            spring:
              #配置rabbitmq信息
              rabbitmq:
                virtual-host: /
                host: localhost
                username: guest
                password: guest
                port: 5672
      bindings:
        output: # channel名称
          binder: my_binder #指定使用哪一个binder
          destination: my_exchage # 消息目的地