# Eureka Server Port
server:
  port: 8761

# Eureka Server Config
eureka:
  instance:
    hostname: localhost
  client: # fixme 为什么 配置EurekaServer's Service URL 需要使用 client ？？？
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false # 是否拿去url
    register-with-eureka: false # 是否注册url
