server:
  port: 81

spring:
  application:
    name: api-gateway

  cloud:
    # 网关配置
    gateway:
      # 路由配置：转发规则
      routes: #集合。
        # id: 唯一标识。默认是一个UUID
        # uri: 转发路径
        # predicates: 条件,用于请求网关路径的匹配规则
        # filters：配置局部过滤器的
        - id: gateway-provider
          # 静态路由
          uri: http://localhost:9001
          predicates:
            - Path=/goods/**

        - id: gateway-consumer
          uri: http://localhost:9002
          predicates:
            - Path=/order/**
